# Generated by Django 2.1 on 2020-02-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='foto',
            field=models.TextField(default='none'),
        ),
    ]
