# Generated by Django 2.1 on 2020-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_vistoria_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoria',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
