# Generated by Django 2.1.12 on 2019-11-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_vistoria_deferido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoria',
            name='contaminacao_agua',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='contaminacao_ar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='contaminacao_solo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_agricultura',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_ambientais_observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_comercio',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_economicos_observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_humanos_afetados',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_humanos_atingidos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_humanos_desabrigados',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_humanos_desalojados',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_humanos_desaparecidos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_humanos_enfermos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_humanos_feridos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_humanos_isolados',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_humanos_mortos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_humanos_observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_industria',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_materiais_observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_pecuaria',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='danos_prestacao_de_servicos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='deferido',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='iah_agua_potavel',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='iah_cestas_de_alimentos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='iah_colchoes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='iah_fornecidos_outros_observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='iah_kit_higiene_pessoal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='iah_kit_limpeza',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='iah_lona_plastica',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='iah_outros',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='iah_telhas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='instalacoes_comunitarias_atingidas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='instalacoes_publicas_ensino_atingidas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='instalacoes_publicas_saude_atingidas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='interrupcoes_servicos_essenciais',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='obras_atingidas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='unidades_habitacionais_atingidas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='unidades_habitacionais_danificads',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='unidades_habitacionais_destruidas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='unidades_habitacionais_interditadas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
