# Generated by Django 2.1 on 2020-02-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_auto_20200217_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='fotoConvertida',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='foto',
            field=models.TextField(),
        ),
    ]
